### ISSUE TITLE
WP CLI does not populate SERVER_ADDR & HTTP_REFERER

### ISSUE THREAD

**Issue by pandjarov** [wp-cli/server-command#20]
I am having issues creating a new command because I can't get SERVER_ADDR and HTTP_REFERER through it.

$_SERVER['SERVER_ADDR'];
$_SERVER['HTTP_REFERER'];

Notice: Undefined index: SERVER_ADDR
Notice: Undefined index: HTTP_REFERER

Any workaround for this?

**Comment by danielbachhuber** [comment]
Hi @pandjarov,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
