### ISSUE TITLE
Set arbitrary document root

### ISSUE THREAD

**Issue by scribu** [wp-cli/server-command#3]
Layout:

```
wp/
index.php
wp-cli.yml
```

If I run `wp server`, the document root should be `.`, not `./wp`.

Previously: #1

**Comment by santagada** [comment]
can you take a look at my pull request? I think it is using the right way to detect wordpress root dir and should just work for 99% of the people. A docroot can be an interesting thing to add but the patch solves the problem using the same way wp-cli uses.

**Comment by scribu** [comment]
Currently looking.

**Comment by Nesk** [comment]
I have the following the project structure:

```
/public # Wordpress files
wp-cli.yml
```

I solved my problem by adding an empty `wp-cli.yml` file in the `public/` directory and by running the `wp server` command in this directory but it would be simpler if @santagada's PR could be merged.

**Comment by nesk** [comment]
Nothing new concerning this issue?

**Comment by scribu** [comment]
Looking at this again, I think having a `root` option would be better than re-using the global `path` argument, which serves a different purpose.

**Comment by nesk** [comment]
In which cas the global `path` couldn't be used? I don't see how this could be a problem.

**Comment by scribu** [comment]
> I don't see how this could be a problem.

Then it means you haven't read this: https://github.com/wp-cli/server-command/pull/8#issuecomment-68869511

**Comment by scribu** [comment]
To avoid confusion, "I don't see how this could be a problem." could be interpreted in at least two ways, so I'm going to treat each one:

* not being able to use the `path` would not be a problem
    * I haven't considered the case when you use `root` and `path` simultaneously

* using the `path` argument instead of `root` would not be a problem
    * as demonstrated by the link above, there would be a problem

**Comment by nesk** [comment]
Oh I see now! Well, it doesn't really matter for me, if a `root` argument is needed I will adapt myself and same goes for other developers.

I will try to work on this feature in the following days.

**Comment by scribu** [comment]
`wp server` is now a core WP-CLI command, with a dedicated `--docroot` option: https://github.com/wp-cli/wp-cli/pull/1858

**Comment by nesk** [comment]
Great work! Many thanks, it will be easier for me from now :)
