### ISSUE TITLE
$_SERVER['SERVER_ADDR'] is missing

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/server-command#48]
It seems `php -S` does not set it.
May I send a PR that sets it to `127.0.0.1` in the router?

**Comment by szepeviktor** [comment]
Alternatively add a --command-line-option to set it...

**Comment by schlessera** [comment]
@szepeviktor I'm not a fan of hardcoding an IP address like that.

How about something like this:
```
$_SERVER['SERVER_ADDR'] = gethostbyname( $_SERVER['SERVER_NAME'] );
```

It would set the `SERVER_ADDR` to the IP address the current hist name resolves to. For `localhost` on my system, this results in it being set to `127.0.0.1`, for example.

Not sure what edge cases we might encounter with this, though...

**Comment by szepeviktor** [comment]
> Not sure what edge cases we might encounter with this, though...

My WAF check for it: https://github.com/szepeviktor/wordpress-fail2ban/blob/master/block-bad-requests/wp-fail2ban-bad-request-instant.inc.php#L150

I send the PR...

**Comment by szepeviktor** [comment]
Thank you.

**Comment by schlessera** [comment]
> Not sure what edge cases we might encounter with this, though...

I was referring to the potential edge cases that might arise by using `gethostbyname( $_SERVER['SERVER_NAME'] )`.

I merged the PR now, I don't know how else to find out, really...
