### ISSUE TITLE
ini file with `auto_prepend_file` doesn't work with router.php

### ISSUE THREAD

**Issue by DanielRuf** [wp-cli/server-command#71]
## Bug Report

It seems loading a config file with `auto_prepend_file` does not work with the `router.php` file.
If I use the internal PHP server without this, it works.

https://github.com/wp-cli/server-command/blob/master/src/Server_Command.php#L90

This works without any problems:

`php -c .../.user.ini -S localhost:8080 -t .`

**Describe the current, buggy behavior**

`php wp-cli.phar server --config=.user.ini`

**Describe how other contributors can replicate this bug**

- create a `.user.ini` file with a `auto_prepend_file` setting
- run `php wp-cli.phar server --config=.user.ini`
- open the browser
- check if the file is actually executed (add an `echo` to it)

**Describe what you would expect as the correct outcome**

The ini file should be loaded and the `auto_prepend_file` setting should work.

**Let us know what environment you are running this on**

```
(Paste the output of "wp cli info" into this box)
```

**Provide a possible solution**

If you happen to have a suggestion on how to fix this bug, please tell us in here.

Just leave this section out if you don't know how to fix it.

**Provide additional context/Screenshots**

If applicable, add screenshots to help explain (you can just drag&drop images into the Github issue).

**Comment by danielbachhuber** [comment]
Thanks for the report, @DanielRuf !

Were you ever able to track down the root cause or identify a workaround?

**Comment by DanielRuf** [comment]
It's because router.php does not look for or load any ini files.

Keep in mind that .user.ini is expected to be in specific folders and PHP has to be configured to look there.

I guess there is no other solution for the PHP CLI - the `c` parameter is probably the right solution for testing.
