### ISSUE TITLE
wp-cli server in the sample installation for some reason does not serve JS or CSS resulting in a broken HTML render

### ISSUE THREAD

**Issue by vadimkantorov** [wp-cli/server-command#81]
I followed https://make.wordpress.org/cli/handbook/how-to/how-to-install/ and https://make.wordpress.org/cli/handbook/how-to/how-to-start-webserver/ to create my first WordPress local installation (serving at 127.0.0.1:8080, calling it as `php wp-cli.phar server --path=./wpssgblog`).

http://127.0.0.1:8080 opens in the web browser, but CSS/JS are not server by the server, so the render is broken.

<img width="772" alt="image" src="https://github.com/wp-cli/server-command/assets/1041752/16104bc3-6288-4329-b187-48369cdf433f">

a CSS http://127.0.0.1:8080/wpssgblog/wp-includes/blocks/navigation/style.min.css/?ver=6.4.2 and http://127.0.0.1:8080/wpssgblog/wp-includes/js/dist/interactivity.min.js/?ver=6.4.2 are some of the resources  that the browser tries to load (`./wpssgblog` is the wordpress dir I'm passing to wp-cli as `--path=./wpssgblog`) serve the exact same HTML for some reason instead of CSS and JS contents. Chrome browser is obviously not happy about this:
<img width="627" alt="image" src="https://github.com/wp-cli/server-command/assets/1041752/c8602a76-c2c5-4b53-aed8-8fef164efa18">

I'm obviously missing something very simple. How can I fix the serve? Thank you :)

**Comment by vadimkantorov** [comment]
Deleting `--path=./wpssgblog` from the server command made it work, by visiting http://127.0.0.1:8080/wpssgblog, but the server log now includes the following error:

```
[Sun Jan 28 21:09:45 2024] 127.0.0.1:62872 Accepted
[Sun Jan 28 21:09:46 2024] 127.0.0.1:62872 [200]: GET /wpssgblog/
[Sun Jan 28 21:09:46 2024] 127.0.0.1:62872 Closing
[Sun Jan 28 21:09:46 2024] 127.0.0.1:62873 Accepted
[Sun Jan 28 21:09:46 2024] 127.0.0.1:62875 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62875 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62877 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62873 [200]: GET /wpssgblog/wp-includes/blocks/navigation/style.min.css?ver=6.4.2
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62878 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62877 [200]: GET /wpssgblog/wp-includes/blocks/image/style.min.css?ver=6.4.2
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62879 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62878 [200]: GET /wpssgblog/wp-content/themes/twentytwentyfour/assets/images/building-exterior.webp
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62880 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62873 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62879 [200]: GET /wpssgblog/wp-content/themes/twentytwentyfour/assets/images/tourist-and-building.webp
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62881 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62877 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62880 [200]: GET /wpssgblog/wp-content/themes/twentytwentyfour/assets/images/windows.webp
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62888 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62881 [200]: GET /wpssgblog/wp-includes/js/dist/interactivity.min.js?ver=6.4.2
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62889 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62878 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62888 [200]: GET /wpssgblog/wp-content/themes/twentytwentyfour/assets/fonts/inter/Inter-VariableFont_slnt,wght.woff2
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62879 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62890 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62880 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62889 [200]: GET /wpssgblog/wp-content/themes/twentytwentyfour/assets/fonts/cardo/cardo_normal_400.woff2
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62891 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62890 [200]: GET /wpssgblog/wp-content/themes/twentytwentyfour/assets/fonts/cardo/cardo_italic_400.woff2
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62881 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62891 [200]: GET /wpssgblog/wp-includes/blocks/navigation/view.min.js?ver=e3d6f3216904b5b42831
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62890 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62888 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62889 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62891 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62892 Accepted
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62892 [200]: GET /wpssgblog/wp-includes/js/wp-emoji-release.min.js?ver=6.4.2
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62892 Closing
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62893 Accepted
[Sun Jan 28 21:09:48 2024] PHP Warning:  require_once(index.php): Failed to open stream: No such file or directory in /tmp/wp-cli-extract-from-phar-65b6b4521f3aa9.36695478-router.php on line 134
[Sun Jan 28 21:09:48 2024] PHP Fatal error:  Uncaught Error: Failed opening required 'index.php' (include_path='.:/usr/share/php') in /tmp/wp-cli-extract-from-phar-65b6b4521f3aa9.36695478-router.php:134
Stack trace:
#0 {main}
  thrown in /tmp/wp-cli-extract-from-phar-65b6b4521f3aa9.36695478-router.php on line 134
[Sun Jan 28 21:09:48 2024] 127.0.0.1:62893 Closing
```

**Comment by vadimkantorov** [comment]
It appears that the server command does not work correctly if launched out-of-the-wordpress-installation-tree? Am I right?

But when I `cd ./wpssgblog && php ../wp-cli.phar server --host=127.0.0.1 --port=8080`, the CSS/JS are also not served, as the URLs continue for some reason to include `/wpssgblog/` prefix for some reason

**Comment by danielbachhuber** [comment]
@vadimkantorov My guess is that you have `http://127.0.0.1:8080/wpssgblog/` set as the `home` or `siteurl` value in your `wp_options` table. When the server starts, that's where WordPress thinks your static assets are and serves the wrong URL.

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
